services:
  - type: web
    name: rico-tours-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: your-database-url
      - key: JWT_SECRET
        value: your-jwt-secret
