services:
  - type: web
    name: rico-tours-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rico-tours-db
          property: connectionString
      - key: JWT_SECRET
        value: your_super_secret_key
      - key: PORT
        value: 3000

databases:
  - name: rico-tours-db
    plan: free
