services:
  - type: web
    name: rico-tours-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ricotoursreservas
          property: connectionString
      - key: JWT_SECRET
        value: z8S1sBewWfcXc9hGTL2tOzbxdq6fCoq8
      - key: PORT
        value: 5432

databases:
  - name: ricotoursreservas
    plan: free
